if (MSVC)
    foreach(header IN LISTS HEADER_FILES)
        get_filename_component(header_path "${header}" PATH)
        file(RELATIVE_PATH header_path_rel "${CMAKE_CURRENT_SOURCE_DIR}/include/na/" "${header_path}")
        string(REPLACE "/" "\\" header_path_rel_msvc "${header_path_rel}")
        source_group("Header Files\\${header_path_rel_msvc}" FILES "${header}")
    endforeach()
    foreach(source IN LISTS SOURCE_FILES)
        get_filename_component(source_path "${source}" PATH)
        file(RELATIVE_PATH source_path_rel "${CMAKE_CURRENT_SOURCE_DIR}/src/na/" "${source_path}")
        string(REPLACE "/" "\\" source_path_rel_msvc "${source_path_rel}")
        source_group("Source Files\\${source_path_rel_msvc}" FILES "${source}")
    endforeach()
    foreach(test IN LISTS TEST_FILES)
        if (${test} STREQUAL ${CMAKE_CURRENT_SOURCE_DIR}/tests.cpp)
            continue()
        endif()
        get_filename_component(test_path "${test}" PATH)
        file(RELATIVE_PATH test_path_rel "${CMAKE_CURRENT_SOURCE_DIR}/tests/" "${test_path}")
        string(REPLACE "/" "\\" test_path_rel_msvc "${test_path_rel}")
        source_group("Source Files\\${test_path_rel_msvc}" FILES "${test}")
    endforeach()
    set(header_ext ".h" ".cuh")
    set(source_ext ".c" ".cpp" ".cu" ".f")
    foreach(driver IN LISTS DRIVER_FILE)
        get_filename_component(driver_ext  "${driver}" EXT)
        get_filename_component(driver_name "${driver}" NAME)
        get_filename_component(driver_path "${driver}" PATH)
        if (${driver_name} MATCHES "^libna")
            continue()
        endif()
        if (driver_ext IN_LIST header_ext)
            file(RELATIVE_PATH driver_path_rel "${CMAKE_CURRENT_SOURCE_DIR}/include/driver/" "${driver_path}")
            string(REPLACE "/" "\\" driver_path_rel_msvc "${driver_path_rel}")
            source_group("Header Files\\${driver_path_rel_msvc}" FILES "${driver}")
        elseif (driver_ext IN_LIST source_ext)
            file(RELATIVE_PATH driver_path_rel "${CMAKE_CURRENT_SOURCE_DIR}/src/driver/" "${driver_path}")
            string(REPLACE "/" "\\" driver_path_rel_msvc "${driver_path_rel}")
            source_group("Source Files\\${driver_path_rel_msvc}" FILES "${driver}")
        endif()
    endforeach()
    unset(header_ext)
    unset(source_ext)
endif()
